"""Generate a LaTeX summary table of template metadata.

Outputs latex_template_metadata.tex with: template name, medical domain,
target node, root nodes, k, n, D_target, and per-root |dT/dx_i| at
CDC population means.
"""
import sys
import os
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))

from utils.med_domain.all_templates import (
    template_target_keys, template_nodes, template_expressions,
    template_layers, CDC_POPULATION_MEANS, get_local_partials,
)
from rootguard.sanitizer import TEMPLATE_DOMAINS
from utils.utils import compute_population_mean_sensitivities

# ── Template definitions ─────────────────────────────────────────────────
TEMPLATES = {
    "ANEMIA":   {"roots": ["hb", "hct", "rbc"],
                 "derived": ["mcv", "mch", "mchc"]},
    "FIB4":     {"roots": ["age", "ast", "alt", "plt"],
                 "derived": ["fib4_prod", "fib4_denom", "fib4"]},
    "AIP":      {"roots": ["tc", "hdl", "tg"],
                 "derived": ["non_hdl", "ldl", "aip"]},
    "CONICITY": {"roots": ["wt", "ht", "waist"],
                 "derived": ["bmi", "wthr", "conicity"]},
    "VASCULAR": {"roots": ["sbp", "dbp"],
                 "derived": ["pp", "map", "mbp", "ppi"]},
    "TYG":      {"roots": ["tg", "glu"],
                 "derived": ["tyg_prod", "tyg_half", "tyg"]},
    "HOMA":     {"roots": ["glu", "ins"],
                 "derived": ["homa_prod", "homa"]},
    "NLR":      {"roots": ["neu", "lym"],
                 "derived": ["nlr_sum", "nlr_diff", "nlr"]},
}

TEMPLATE_ORDER = ["ANEMIA", "FIB4", "AIP", "CONICITY",
                  "VASCULAR", "TYG", "HOMA", "NLR"]

DOMAIN_LABELS = {
    "ANEMIA": "Hematology", "FIB4": "Hepatology", "AIP": "Cardiology",
    "CONICITY": "Anthropometry", "VASCULAR": "Hemodynamics",
    "TYG": "Metabolic", "HOMA": "Metabolic", "NLR": "Immunology",
}

TARGET_PRETTY = {
    "ANEMIA": "MCHC", "AIP": "AIP", "CONICITY": "CI",
    "VASCULAR": "PPI", "FIB4": "FIB-4", "TYG": "TyG",
    "HOMA": "HOMA-IR", "NLR": "NLR",
}

ROOT_PRETTY = {
    "hb": "Hb", "hct": "Hct", "rbc": "RBC",
    "age": "Age", "ast": "AST", "alt": "ALT", "plt": "PLT",
    "tc": "TC", "hdl": "HDL", "tg": "TG",
    "wt": "Wt", "ht": "Ht", "waist": "Waist",
    "sbp": "SBP", "dbp": "DBP",
    "glu": "Glu", "ins": "Ins",
    "neu": "Neu", "lym": "Lym",
}

# Classification nodes to skip in topo traversal
SKIP_NODES = [
    "anemia_class", "fib4_risk", "aip_risk", "ci_risk",
    "ppi_risk", "tyg_class", "homa_class", "nlr_class",
]


def get_template_topo(roots, derived):
    """Return template-specific topological order: roots then derived."""
    return roots + derived


def fmt_sens(v):
    """Format sensitivity value compactly."""
    if v == 0:
        return "0"
    elif v >= 100:
        return "{:.0f}".format(v)
    elif v >= 10:
        return "{:.1f}".format(v)
    elif v >= 1:
        return "{:.2f}".format(v)
    elif v >= 0.01:
        return "{:.3f}".format(v)
    else:
        return "{:.1e}".format(v)


def fmt_domain(v):
    """Format domain width."""
    if v >= 100:
        return "{:.0f}".format(v)
    elif v >= 10:
        return "{:.1f}".format(v)
    else:
        return "{:.2f}".format(v)


# ── Compute all data ─────────────────────────────────────────────────────
rows = []
for tmpl in TEMPLATE_ORDER:
    target = template_target_keys[tmpl]
    roots = TEMPLATES[tmpl]["roots"]
    derived = TEMPLATES[tmpl]["derived"]
    k = len(roots)
    n = k + len(derived)  # total non-classification nodes

    # Target domain width
    tdom = TEMPLATE_DOMAINS[tmpl]
    d_target = tdom[target][1] - tdom[target][0]

    # Template-specific topo order
    topo_order = get_template_topo(roots, derived)

    # Per-root sensitivities at population means
    sens = compute_population_mean_sensitivities(
        target, roots, template_expressions,
        SKIP_NODES, topo_order, template_nodes,
        CDC_POPULATION_MEANS
    )

    rows.append({
        "tmpl": tmpl,
        "domain": DOMAIN_LABELS[tmpl],
        "target": TARGET_PRETTY[tmpl],
        "roots": roots,
        "k": k,
        "n": n,
        "d_target": d_target,
        "sens": sens,
    })

# ── Generate LaTeX ───────────────────────────────────────────────────────
out = []
out.append(r"% Auto-generated by gen_template_metadata_table.py")
out.append(r"")
out.append(r"\begin{table*}[t]")
out.append(r"\centering")
out.append(r"\small")
out.append(r"\caption{Clinical template metadata. Each template defines a DAG from root laboratory measurements to a clinical target index. $k$: number of root nodes; $n$: total numeric nodes (roots + intermediates + target); $D_T$: target domain width (NHANES observed range); $|\partial T / \partial x_i|_{\bar{x}}$: absolute end-to-end sensitivity of the target to each root, evaluated at CDC population means via forward-mode AD through the DAG.}")
out.append(r"\label{tab:template-metadata}")
out.append(r"\setlength{\tabcolsep}{4pt}")
out.append(r"\begin{tabular}{llllccrl}")
out.append(r"\toprule")
out.append(r"\textbf{Template} & \textbf{Domain} & \textbf{Target} & \textbf{Roots} & $k$ & $n$ & $D_T$ & $|\partial T / \partial x_i|_{\bar{x}}$ \\")
out.append(r"\midrule")

for row in rows:
    roots_str = ", ".join(ROOT_PRETTY[r] for r in row["roots"])

    # Build sensitivity string: "Root1: val, Root2: val, ..."
    sens_parts = []
    for r in row["roots"]:
        v = row["sens"][r]
        sens_parts.append("{}: {}".format(ROOT_PRETTY[r], fmt_sens(v)))
    sens_str = ", ".join(sens_parts)

    out.append(
        "{tmpl} & {domain} & {target} & {roots} & {k} & {n} & {dt} & "
        "\\footnotesize {{{sens}}} \\\\".format(
            tmpl=row["tmpl"],
            domain=row["domain"],
            target=row["target"],
            roots=roots_str,
            k=row["k"],
            n=row["n"],
            dt=fmt_domain(row["d_target"]),
            sens=sens_str,
        )
    )

out.append(r"\bottomrule")
out.append(r"\end{tabular}")
out.append(r"\end{table*}")
out.append("")

with open("latex_template_metadata.tex", "w") as f:
    f.write("\n".join(out) + "\n")

print("Written {} lines to latex_template_metadata.tex".format(len(out)))

# Print summary for verification
print("\nVerification summary:")
print("{:<10} {:<14} {:<8} {:>5} {:>3} {:>3} {:>8}  {}".format(
    "Template", "Domain", "Target", "k", "n", "D_T", "", "Sensitivities"))
print("-" * 90)
for row in rows:
    sens_str = ", ".join(
        "{}={:.4f}".format(ROOT_PRETTY[r], row["sens"][r])
        for r in row["roots"]
    )
    print("{:<10} {:<14} {:<8} {:>3} {:>3} {:>8.2f}  {}".format(
        row["tmpl"], row["domain"], row["target"],
        row["k"], row["n"], row["d_target"], sens_str))
