"""Generate appendix tables for RQ1 adversarial experiments.

Covers budget modes: k+1, 2k+1, 3k+1.
Outputs latex_rq1_adversarial_summary.tex with:
  - Appendix section header and description
  - For each budget mode: aggregate wMAPE (with SEs), aggregate RCE, per-template wMAPE at eps=0.1 (with SEs)
  - Win rate summary table
"""
import json
import numpy as np

TEMPLATES = ['ANEMIA', 'FIB4', 'AIP', 'CONICITY', 'VASCULAR', 'TYG', 'HOMA', 'NLR']
K = {'ANEMIA': 3, 'FIB4': 4, 'AIP': 3, 'CONICITY': 3,
     'VASCULAR': 2, 'TYG': 2, 'HOMA': 2, 'NLR': 2}
EPS_VALS = [5.0, 2.0, 1.0, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005]
METHODS = [
    'exp_all', 'exp_roots', 'exp_opt',
    'blap_all', 'blap_roots', 'blap_opt',
    'stair_all', 'stair_roots', 'stair_opt',
]

RUNS = [
    ('kplus1',  'k+1',  'results_rq1_adversarial_kplus1_wmape',  lambda k: k + 1),
    ('2kplus1', '2k+1', 'results_rq1_adversarial_2kplus1_wmape', lambda k: 2 * k + 1),
    ('3kplus1', '3k+1', 'results_rq1_adversarial_3kplus1_wmape', lambda k: 3 * k + 1),
]


def load(base, eps, tmpl, method):
    fname = '{}/epsilon_{}/{}/{}_results.json'.format(base, eps, tmpl, method)
    with open(fname) as f:
        return json.load(f)['summary']


def fmt(v):
    if v >= 100:
        return '{:.0f}'.format(v)
    else:
        return '{:.1f}'.format(v)


def fmt_se(v):
    if v >= 10:
        return '{:.0f}'.format(v)
    else:
        return '{:.1f}'.format(v)


def aggregate_with_se(data, eps, method):
    """Return (mean_wmape, se_wmape) aggregated across templates."""
    summaries = [data[eps][t][method] for t in TEMPLATES]
    mean = np.mean([s['wmape'] for s in summaries])
    se = np.sqrt(np.sum(np.array([s['wmape_se'] for s in summaries]) ** 2)) / len(TEMPLATES)
    return mean, se


out = []

# ── Header ───────────────────────────────────────────────────────────────
out.append('\\providecommand{\\pmstd}[1]{{\\scriptsize $\\pm$#1}}')
out.append('')
out.append('%% ======================================================================')
out.append('%% Appendix: RQ1 Adversarial Experiments — Full Tables')
out.append('%% Auto-generated by gen_rq1_adversarial_summary.py')
out.append('%% ======================================================================')
out.append('')

# ── Appendix section ────────────────────────────────────────────────────
out.append('\\section{RQ1: Full Adversarial Utility Tables}')
out.append('\\label{app:rq1-tables}')
out.append('')
out.append('This appendix provides the complete aggregate wMAPE and Risk Class Error tables for all three mechanisms (Exponential, Bounded Laplace, Staircase) under each of the three adversary budget levels ($B = (k{+}1)\\varepsilon$, $(2k{+}1)\\varepsilon$, $(3k{+}1)\\varepsilon$). Per-template breakdowns at $\\varepsilon = 0.1$ are also included. The main text (Sec.~\\ref{sec:experiments-rq1}) reports the Exponential mechanism; the Bounded Laplace and Staircase results follow the same trends. Bootstrap standard errors (1000 resamples) are shown inline as {\\scriptsize $\\pm$SE}.')
out.append('')

# ── Per-run tables ───────────────────────────────────────────────────────
for run_key, run_label, base, budget_fn in RUNS:
    # Preload all data for this run
    data = {}
    for eps in EPS_VALS:
        data[eps] = {}
        for tmpl in TEMPLATES:
            data[eps][tmpl] = {}
            for m in METHODS:
                data[eps][tmpl][m] = load(base, eps, tmpl, m)

    suffix = run_key

    # --- Aggregate wMAPE with SEs ---
    out.append('\\begin{table*}[t]')
    out.append('\\centering')
    out.append('\\setlength{\\tabcolsep}{2.8pt}')
    out.append('\\small')
    out.append('\\caption{{Aggregate wMAPE (\\%) averaged across 8 templates with bootstrap SE. Budget $B = ({}) \\cdot \\varepsilon$. Best mean per row in \\textbf{{bold}}.}}'.format(run_label))
    out.append('\\label{{tab:rq1_{}_wmape}}'.format(suffix))
    out.append('\\begin{tabular}{cc|ccc|ccc|ccc}')
    out.append('\\toprule')
    out.append('& & \\multicolumn{3}{c|}{\\textbf{Exponential}} & \\multicolumn{3}{c|}{\\textbf{Bounded Laplace}} & \\multicolumn{3}{c}{\\textbf{Staircase}} \\\\')
    out.append('$\\varepsilon$ & $\\bar{B}$ & All & Roots & Opt & All & Roots & Opt & All & Roots & Opt \\\\')
    out.append('\\midrule')

    for eps in EPS_VALS:
        row_data = []  # list of (mean, se) tuples
        for m in METHODS:
            mean, se = aggregate_with_se(data, eps, m)
            row_data.append((mean, se))

        means = [d[0] for d in row_data]
        best_idx = min(range(9), key=lambda i: means[i])

        cells = []
        for i, (m, se) in enumerate(row_data):
            val = '{}\\pmstd{{{}}}'.format(fmt(m), fmt_se(se))
            if i == best_idx:
                cells.append('\\textbf{{{}}}'.format(val))
            else:
                cells.append(val)

        avg_b = np.mean([budget_fn(K[t]) * eps for t in TEMPLATES])
        out.append('{} & {:.2f} & {} \\\\'.format(eps, avg_b, ' & '.join(cells)))

    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table*}')
    out.append('')

    # --- Aggregate RCE (no SE — risk_mae doesn't have wmape_se) ---
    out.append('\\begin{table*}[t]')
    out.append('\\centering')
    out.append('\\setlength{\\tabcolsep}{3.0pt}')
    out.append('\\small')
    out.append('\\caption{{Aggregate Risk Class Error (\\%) averaged across 8 templates. Budget $B = ({}) \\cdot \\varepsilon$. Best per row in \\textbf{{bold}}.}}'.format(run_label))
    out.append('\\label{{tab:rq1_{}_rce}}'.format(suffix))
    out.append('\\begin{tabular}{cc|ccc|ccc|ccc}')
    out.append('\\toprule')
    out.append('& & \\multicolumn{3}{c|}{\\textbf{Exponential}} & \\multicolumn{3}{c|}{\\textbf{Bounded Laplace}} & \\multicolumn{3}{c}{\\textbf{Staircase}} \\\\')
    out.append('$\\varepsilon$ & $\\bar{B}$ & All & Roots & Opt & All & Roots & Opt & All & Roots & Opt \\\\')
    out.append('\\midrule')

    for eps in EPS_VALS:
        row_means = []
        for m in METHODS:
            per_tmpl = [data[eps][t][m]['risk_mae'] for t in TEMPLATES]
            row_means.append(np.mean(per_tmpl))
        best_idx = min(range(9), key=lambda i: row_means[i])
        cells = []
        for i, v in enumerate(row_means):
            s = fmt(v)
            if i == best_idx:
                cells.append('\\textbf{{{}}}'.format(s))
            else:
                cells.append(s)
        avg_b = np.mean([budget_fn(K[t]) * eps for t in TEMPLATES])
        out.append('{} & {:.2f} & {} \\\\'.format(eps, avg_b, ' & '.join(cells)))

    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table*}')
    out.append('')

    # --- Per-template wMAPE at eps=0.1 with SEs ---
    eps_d = 0.1
    avg_b_d = np.mean([budget_fn(K[t]) * eps_d for t in TEMPLATES])
    out.append('\\begin{table*}[t]')
    out.append('\\centering')
    out.append('\\setlength{\\tabcolsep}{2.8pt}')
    out.append('\\small')
    out.append('\\caption{{Per-template wMAPE (\\%) with bootstrap SE at $\\varepsilon = 0.1$ ($\\bar{{B}} = {:.2f}$). Budget $B = ({}) \\cdot \\varepsilon$. Best per row in \\textbf{{bold}}.}}'.format(avg_b_d, run_label))
    out.append('\\label{{tab:rq1_{}_per_tmpl_wmape}}'.format(suffix))
    out.append('\\begin{tabular}{l|ccc|ccc|ccc}')
    out.append('\\toprule')
    out.append('& \\multicolumn{3}{c|}{\\textbf{Exponential}} & \\multicolumn{3}{c|}{\\textbf{Bounded Laplace}} & \\multicolumn{3}{c}{\\textbf{Staircase}} \\\\')
    out.append('Template & All & Roots & Opt & All & Roots & Opt & All & Roots & Opt \\\\')
    out.append('\\midrule')
    for tmpl in TEMPLATES:
        vals = []
        for m in METHODS:
            s = data[eps_d][tmpl][m]
            vals.append((s['wmape'], s['wmape_se']))
        means = [v[0] for v in vals]
        best_idx = min(range(9), key=lambda i: means[i])
        cells = []
        for i, (m, se) in enumerate(vals):
            val = '{}\\pmstd{{{}}}'.format(fmt(m), fmt_se(se))
            if i == best_idx:
                cells.append('\\textbf{{{}}}'.format(val))
            else:
                cells.append(val)
        out.append('{} & {} \\\\'.format(tmpl, ' & '.join(cells)))
    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table*}')
    out.append('')

# ── Win rate summary table ───────────────────────────────────────────────
out.append('\\begin{table}[t]')
out.append('\\centering')
out.append('\\small')
out.append('\\caption{$\\mathcal{M}$-Opt vs.\\ $\\mathcal{M}$-All win rate per template (across 3 mechanisms $\\times$ 10 $\\varepsilon$ values = 30 pairs). A win means $\\mathcal{M}$-Opt achieves lower wMAPE than $\\mathcal{M}$-All for the same mechanism and $\\varepsilon$.}')
out.append('\\label{tab:rq1_win_rate_app}')
out.append('\\begin{tabular}{lcccc}')
out.append('\\toprule')
out.append('\\textbf{Template} & $k$ & $k{+}1$ & $2k{+}1$ & $3k{+}1$ \\\\')
out.append('\\midrule')

totals = {r[0]: [0, 0] for r in RUNS}
for tmpl in TEMPLATES:
    line = '{} & {}'.format(tmpl, K[tmpl])
    for run_key, run_label, base, budget_fn in RUNS:
        wins = 0
        for mech in ['exp', 'blap', 'stair']:
            for eps in EPS_VALS:
                a = load(base, eps, tmpl, '{}_all'.format(mech))['wmape']
                o = load(base, eps, tmpl, '{}_opt'.format(mech))['wmape']
                if o < a:
                    wins += 1
        totals[run_key][0] += wins
        totals[run_key][1] += 30
        line += ' & {}/30'.format(wins)
    line += ' \\\\'
    out.append(line)

out.append('\\midrule')
total_line = '\\textbf{Total} & '
for run_key, run_label, base, budget_fn in RUNS:
    w, t = totals[run_key]
    total_line += '& {}/{} ({:.0f}\\%)'.format(w, t, 100 * w / t)
total_line += ' \\\\'
out.append(total_line)
out.append('\\bottomrule')
out.append('\\end{tabular}')
out.append('\\end{table}')
out.append('')

with open('latex_rq1_adversarial_summary.tex', 'w') as f:
    f.write('\n'.join(out) + '\n')
print('Written {} lines to latex_rq1_adversarial_summary.tex'.format(len(out)))
